modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="eriniumrank"
version="1.0.0"
displayName="Erinium Rank"
credits="Created by JLSkyzer"
displayURL="https://github.com/JLSkyzer/EriniumRank/tree/main"
authors="JLSkyzer"

[[dependencies.eriniumrank]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




