modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="eriniumrank"
version="1.0.0"
displayName="Erinium Rank"
displayURL="https://github.com/JLSkyzer/EriniumRank/tree/main"
credits="Created by JLSkyzer"
authors="JLSkyzer"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "eriniumrank.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.eriniumrank]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.eriniumrank]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration